name: Vertex AI Model Deployment
on:
  workflow_run:
    workflows: ["Train Model Pipeline"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
      GCP_REGION: us-central1
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Get Training Output
      id: training
      run: |
        MODEL_URI=$(gsutil ls gs://$GCP_PROJECT-model-outputs/ | grep -v "/$" | tail -1)
        echo "MODEL_URI=$MODEL_URI" >> $GITHUB_OUTPUT
        echo "MODEL_DIR=$(dirname $MODEL_URI)" >> $GITHUB_OUTPUT

    - name: Create or Reuse Endpoint
      id: endpoint
      run: |
        ENDPOINT_ID=$(gcloud ai endpoints list \
          --region=$GCP_REGION \
          --filter="displayName=iris-endpoint" \
          --format="value(name)" | head -1)
        
        if [ -z "$ENDPOINT_ID" ]; then
          ENDPOINT_ID=$(gcloud ai endpoints create \
            --display-name=iris-endpoint \
            --region=$GCP_REGION \
            --format="value(name)")
        fi
        echo "ENDPOINT_ID=$ENDPOINT_ID" >> $GITHUB_OUTPUT

    - name: Register Model
      id: model
      run: |
        MODEL_ID=$(gcloud ai models upload \
          --region=$GCP_REGION \
          --display-name="iris-model-$(date +%Y%m%d-%H%M%S)" \
          --container-image-uri=gcr.io/$GCP_PROJECT/ml-pipeline:prod-final \
          --artifact-uri=${{ steps.training.outputs.MODEL_DIR }} \
          --format="value(name)")
        echo "MODEL_ID=$MODEL_ID" >> $GITHUB_OUTPUT

    - name: Deploy Model
      run: |
        gcloud ai endpoints deploy-model ${{ steps.endpoint.outputs.ENDPOINT_ID }} \
          --region=$GCP_REGION \
          --model=${{ steps.model.outputs.MODEL_ID }} \
          --display-name="iris-production" \
          --machine-type=n1-standard-4 \
          --min-replica-count=1 \
          --max-replica-count=2 \
          --traffic-split=0=100

    - name: Verify Deployment
      run: |
        gcloud ai endpoints describe ${{ steps.endpoint.outputs.ENDPOINT_ID }} \
          --region=$GCP_REGION \
          --format="value(deployedModels.id)" | grep -q "." || exit 1