name: Train Model Pipeline
on:
  push:
    branches: [ main ]
    paths:
      - 'src/main/**'
      - 'datasets/**'

jobs:
  train:
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
      GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Build and Train
      run: |
        mvn clean package
        java -Dgcs.bucket=$GCS_BUCKET \
             -cp target/ml-pipeline-1.0.jar \
             com.healthvision.ml.Trainer
        
    - name: Upload Model to Vertex AI
      run: |
        gcloud ai models upload \
          --region=us-central1 \
          --display-name=iris-model \
          --container-image-uri=us-docker.pkg.dev/vertex-ai/prediction/sklearn-cpu.1-0:latest \
          --artifact-uri=gs://$GCS_BUCKET/models/